
import { Category, PhraseItem } from './types';

export const ROOT_CATEGORIES: PhraseItem[] = [
  { id: 'cat-do', label: 'DO', emoji: '🎬', category: Category.ROOT, isFolder: true, targetCategory: Category.DO },
  { id: 'cat-eat', label: 'EAT', emoji: '🍽️', category: Category.ROOT, isFolder: true, targetCategory: Category.EAT },
  { id: 'cat-go', label: 'GO', emoji: '🚶', category: Category.ROOT, isFolder: true, targetCategory: Category.GO },
  { id: 'cat-tell', label: 'TELL', emoji: '🗣️', category: Category.ROOT, isFolder: true, targetCategory: Category.TELL },
  { id: 'cat-might', label: 'MIGHT', emoji: '💡', category: Category.ROOT, isFolder: true, targetCategory: Category.MIGHT },
  { id: 'cat-things', label: 'THINGS', emoji: '🏔️', category: Category.ROOT, isFolder: true, targetCategory: Category.THINGS },
  { id: 'cat-tool', label: 'TOOL', emoji: '🛠️', category: Category.ROOT, isFolder: true, targetCategory: Category.TOOL },
  { id: 'cat-material', label: 'MATERIAL', emoji: '🎨', category: Category.ROOT, isFolder: true, targetCategory: Category.MATERIAL },
  { id: 'cat-isbe', label: 'IS / BE', emoji: '✨', category: Category.ROOT, isFolder: true, targetCategory: Category.IS_BE },
  { id: 'cat-look', label: 'LOOK', emoji: '🔍', category: Category.ROOT, isFolder: true, targetCategory: Category.LOOK },
  { id: 'cat-wear', label: 'WEAR', emoji: '👕', category: Category.ROOT, isFolder: true, targetCategory: Category.WEAR },
  { id: 'cat-body', label: 'BODY', emoji: '👤', category: Category.ROOT, isFolder: true, targetCategory: Category.BODY },
  { id: 'cat-touch', label: 'TOUCH', emoji: '🖐️', category: Category.ROOT, isFolder: true, targetCategory: Category.TOUCH },
  { id: 'cat-people', label: 'PEOPLE', emoji: '👨‍👩‍👧‍👦', category: Category.ROOT, isFolder: true, targetCategory: Category.PEOPLE },
  { id: 'cat-what', label: 'WHAT', emoji: '❓', category: Category.ROOT, isFolder: true, targetCategory: Category.WHAT },
  { id: 'cat-when', label: 'WHEN', emoji: '⏰', category: Category.ROOT, isFolder: true, targetCategory: Category.WHEN },
];

export const VOCABULARY: Record<Category, PhraseItem[]> = {
  [Category.ROOT]: ROOT_CATEGORIES,
  
  [Category.DO]: [
    { id: 'do1', label: 'Love', emoji: '❤️', category: Category.DO },
    { id: 'do2', label: 'Like', emoji: '👍', category: Category.DO },
    { id: 'do3', label: 'Need', emoji: '✋', category: Category.DO },
    { id: 'do4', label: 'Try', emoji: '💪', category: Category.DO },
    { id: 'do5', label: 'Help', emoji: '🆘', category: Category.DO },
    { id: 'do6', label: 'Come', emoji: '👋', category: Category.DO },
    { id: 'do7', label: 'Wait', emoji: '⏳', category: Category.DO },
    { id: 'do8', label: 'Smell', emoji: '👃', category: Category.DO },
    { id: 'do9', label: 'Get', emoji: '🤲', category: Category.DO },
    { id: 'do10', label: 'Make', emoji: '🔨', category: Category.DO },
    { id: 'do11', label: 'Use', emoji: '⚙️', category: Category.DO },
    { id: 'do12', label: 'Sleep', emoji: '💤', category: Category.DO },
    { id: 'do13', label: 'Wake', emoji: '☀️', category: Category.DO },
    { id: 'do14', label: 'See', emoji: '👁️', category: Category.DO },
    { id: 'do15', label: 'Know', emoji: '🧠', category: Category.DO },
    { id: 'do16', label: 'Read', emoji: '📖', category: Category.DO },
    { id: 'do17', label: 'Have', emoji: '🎒', category: Category.DO },
    { id: 'do18', label: 'Feel', emoji: '💖', category: Category.DO },
  ],

  [Category.EAT]: [
    { id: 'eat1', label: 'Water', emoji: '💧', category: Category.EAT },
    { id: 'eat2', label: 'Taste', emoji: '👅', category: Category.EAT },
    { id: 'eat3', label: 'Drink', emoji: '🥤', category: Category.EAT },
    { id: 'eat4', label: 'Eat', emoji: '🍴', category: Category.EAT },
    { id: 'eat5', label: 'Food', emoji: '🍱', category: Category.EAT },
    { id: 'eat6', label: 'Yogurt', emoji: '🥣', category: Category.EAT },
    { id: 'eat7', label: 'Milk', emoji: '🥛', category: Category.EAT },
    { id: 'eat8', label: 'Bite', emoji: '🦷', category: Category.EAT },
    { id: 'eat9', label: 'Thirsty', emoji: '🥵', category: Category.EAT },
    { id: 'eat10', label: 'Full', emoji: '🤰', category: Category.EAT },
    { id: 'eat11', label: 'Bread', emoji: '🍞', category: Category.EAT },
    { id: 'eat12', label: 'Groceries', emoji: '🛍️', category: Category.EAT },
    { id: 'eat13', label: 'Juice', emoji: '🧃', category: Category.EAT },
    { id: 'eat14', label: 'Hungry', emoji: '🤤', category: Category.EAT },
    { id: 'eat15', label: 'Empty', emoji: '📭', category: Category.EAT },
    { id: 'eat16', label: 'Meat', emoji: '🥩', category: Category.EAT },
    { id: 'eat17', label: 'Vegetables', emoji: '🥦', category: Category.EAT },
    { id: 'eat18', label: 'Breakfast', emoji: '🍳', category: Category.EAT },
    { id: 'eat19', label: 'Lunch', emoji: '🥪', category: Category.EAT },
    { id: 'eat20', label: 'Dinner', emoji: '🍝', category: Category.EAT },
    { id: 'eat21', label: 'Snack', emoji: '🍿', category: Category.EAT },
    { id: 'eat22', label: 'Cheese', emoji: '🧀', category: Category.EAT },
    { id: 'eat23', label: 'Chips', emoji: '🍟', category: Category.EAT },
    { id: 'fruit1', label: 'Apple', emoji: '🍎', category: Category.EAT },
    { id: 'fruit2', label: 'Banana', emoji: '🍌', category: Category.EAT },
    { id: 'fruit3', label: 'Grapes', emoji: '🍇', category: Category.EAT },
    { id: 'fruit4', label: 'Strawberry', emoji: '🍓', category: Category.EAT },
    { id: 'fruit5', label: 'Orange', emoji: '🍊', category: Category.EAT },
    { id: 'fruit6', label: 'Watermelon', emoji: '🍉', category: Category.EAT },
  ],

  [Category.GO]: [
    { id: 'go1', label: 'Home', emoji: '🏠', category: Category.GO },
    { id: 'go2', label: 'My Room', emoji: '🛏️', category: Category.GO },
    { id: 'go3', label: 'Bathroom', emoji: '🚽', category: Category.GO },
    { id: 'go4', label: 'Way', emoji: '🛤️', category: Category.GO },
    { id: 'go5', label: 'Inside', emoji: '🚪', category: Category.GO },
    { id: 'go6', label: 'Outside', emoji: '🌳', category: Category.GO },
    { id: 'go7', label: 'At', emoji: '📍', category: Category.GO },
    { id: 'go8', label: 'Go', emoji: '🏃', category: Category.GO },
    { id: 'go9', label: 'Where', emoji: '❓', category: Category.GO },
    { id: 'go10', label: 'Place', emoji: '🗺️', category: Category.GO },
    { id: 'go11', label: 'Upstairs', emoji: '⬆️', category: Category.GO },
    { id: 'go12', label: 'Downstairs', emoji: '⬇️', category: Category.GO },
    { id: 'go13', label: 'Church', emoji: '⛪', category: Category.GO },
    { id: 'go14', label: 'Hospital', emoji: '🏥', category: Category.GO },
    { id: 'go15', label: 'School', emoji: '🏫', category: Category.GO },
    { id: 'go16', label: 'Here', emoji: '📌', category: Category.GO },
    { id: 'go17', label: 'There', emoji: '👉', category: Category.GO },
    { id: 'go18', label: 'House', emoji: '🏡', category: Category.GO },
    { id: 'go19', label: 'Library', emoji: '📚', category: Category.GO },
    { id: 'go20', label: 'Store', emoji: '🛒', category: Category.GO },
    { id: 'go21', label: 'Away', emoji: '🛫', category: Category.GO },
    { id: 'go22', label: 'Direction', emoji: '🧭', category: Category.GO },
  ],

  [Category.TELL]: [
    { id: 'tell1', label: 'Yes', emoji: '✅', category: Category.TELL },
    { id: 'tell2', label: 'No', emoji: '❌', category: Category.TELL },
    { id: 'tell3', label: 'Okay', emoji: '👌', category: Category.TELL },
    { id: 'tell4', label: 'Ask', emoji: '🙋', category: Category.TELL },
    { id: 'tell5', label: 'Talk', emoji: '🗣️', category: Category.TELL },
    { id: 'tell6', label: 'Say', emoji: '💬', category: Category.TELL },
    { id: 'tell7', label: 'Hello', emoji: '👋', category: Category.TELL },
    { id: 'tell8', label: 'Please', emoji: '🙏', category: Category.TELL },
    { id: 'tell9', label: 'Thank You', emoji: '💖', category: Category.TELL },
    { id: 'tell10', label: 'Sorry', emoji: '🙇', category: Category.TELL },
    { id: 'tell11', label: 'My Turn', emoji: '👉', category: Category.TELL },
    { id: 'tell12', label: 'Your Turn', emoji: '👈', category: Category.TELL },
    { id: 'tell13', label: 'Think', emoji: '🤔', category: Category.TELL },
    { id: 'tell14', label: 'Remember', emoji: '🧠', category: Category.TELL },
    { id: 'tell15', label: 'Listen', emoji: '👂', category: Category.TELL },
    { id: 'tell16', label: 'Hear', emoji: '🔔', category: Category.TELL },
    { id: 'tell17', label: 'Because', emoji: '🔗', category: Category.TELL },
    { id: 'tell18', label: 'Write', emoji: '📝', category: Category.TELL },
    { id: 'tell19', label: 'Call', emoji: '📞', category: Category.TELL },
    { id: 'tell20', label: 'Learn', emoji: '🎓', category: Category.TELL },
    { id: 'tell21', label: 'Sound', emoji: '🔊', category: Category.TELL },
    { id: 'tell22', label: 'Guess', emoji: '🎲', category: Category.TELL },
    { id: 'tell23', label: 'Good', emoji: '🌟', category: Category.TELL },
  ],

  [Category.MIGHT]: [
    { id: 'm1', label: 'Could', emoji: '❓', category: Category.MIGHT },
    { id: 'm2', label: 'Would', emoji: '💭', category: Category.MIGHT },
    { id: 'm3', label: 'Should', emoji: '⚖️', category: Category.MIGHT },
    { id: 'm4', label: 'May', emoji: '🍃', category: Category.MIGHT },
    { id: 'm5', label: 'Must', emoji: '❗', category: Category.MIGHT },
    { id: 'm6', label: 'Definitely', emoji: '💯', category: Category.MIGHT },
    { id: 'm7', label: 'Also', emoji: '➕', category: Category.MIGHT },
    { id: 'm8', label: 'Instead', emoji: '🔄', category: Category.MIGHT },
    { id: 'm9', label: 'Still', emoji: '⏸️', category: Category.MIGHT },
    { id: 'm10', label: 'Again', emoji: '🔁', category: Category.MIGHT },
    { id: 'm11', label: 'Almost', emoji: '🤏', category: Category.MIGHT },
    { id: 'm12', label: 'Even', emoji: '➖', category: Category.MIGHT },
    { id: 'm13', label: 'This', emoji: '👇', category: Category.MIGHT },
    { id: 'm14', label: 'That', emoji: '👉', category: Category.MIGHT },
    { id: 'm15', label: 'Very', emoji: '💥', category: Category.MIGHT },
    { id: 'm16', label: 'Too', emoji: '😵', category: Category.MIGHT },
    { id: 'm17', label: 'Game', emoji: '🎮', category: Category.MIGHT },
    { id: 'm18', label: 'Job', emoji: '💼', category: Category.MIGHT },
    { id: 'm19', label: 'Sky', emoji: '☁️', category: Category.MIGHT },
  ],

  [Category.THINGS]: [
    { id: 'th1', label: 'Ocean', emoji: '🌊', category: Category.THINGS },
    { id: 'th2', label: 'Lake', emoji: '💧', category: Category.THINGS },
    { id: 'th3', label: 'Mountain', emoji: '🏔️', category: Category.THINGS },
    { id: 'th4', label: 'Road', emoji: '🛣️', category: Category.THINGS },
    { id: 'th5', label: 'Bridge', emoji: '🌉', category: Category.THINGS },
    { id: 'th6', label: 'Flower', emoji: '🌸', category: Category.THINGS },
    { id: 'th7', label: 'Tree', emoji: '🌳', category: Category.THINGS },
    { id: 'th8', label: 'Forest', emoji: '🌲', category: Category.THINGS },
    { id: 'th9', label: 'Car', emoji: '🚗', category: Category.THINGS },
    { id: 'th10', label: 'Bus', emoji: '🚌', category: Category.THINGS },
    { id: 'th11', label: 'Boat', emoji: '⛵', category: Category.THINGS },
    { id: 'th12', label: 'Thing', emoji: '📦', category: Category.THINGS },
    { id: 'th13', label: 'Pet', emoji: '🐾', category: Category.THINGS },
    { id: 'th14', label: 'Dog', emoji: '🐶', category: Category.THINGS },
    { id: 'th15', label: 'Cat', emoji: '🐱', category: Category.THINGS },
    { id: 'th16', label: 'Animal', emoji: '🦁', category: Category.THINGS },
    { id: 'th17', label: 'Bug', emoji: '🐞', category: Category.THINGS },
  ],

  [Category.TOOL]: [
    { id: 'tl1', label: 'Hammer', emoji: '🔨', category: Category.TOOL },
    { id: 'tl2', label: 'Screwdriver', emoji: '🪛', category: Category.TOOL },
    { id: 'tl3', label: 'Tools', emoji: '🛠️', category: Category.TOOL },
    { id: 'tl4', label: 'Pencil', emoji: '✏️', category: Category.TOOL },
    { id: 'tl5', label: 'Pen', emoji: '🖊️', category: Category.TOOL },
    { id: 'tl6', label: 'Plate', emoji: '🍽️', category: Category.TOOL },
    { id: 'tl7', label: 'Knife', emoji: '🔪', category: Category.TOOL },
    { id: 'tl8', label: 'Fork', emoji: '🍴', category: Category.TOOL },
    { id: 'tl9', label: 'Spoon', emoji: '🥄', category: Category.TOOL },
    { id: 'tl10', label: 'Bowl', emoji: '🥣', category: Category.TOOL },
    { id: 'tl11', label: 'Cup', emoji: '🥤', category: Category.TOOL },
  ],

  [Category.MATERIAL]: [
    { id: 'mat1', label: 'Wood', emoji: '🪵', category: Category.MATERIAL },
    { id: 'mat2', label: 'Fire', emoji: '🔥', category: Category.MATERIAL },
    { id: 'mat3', label: 'Paper', emoji: '📄', category: Category.MATERIAL },
    { id: 'mat4', label: 'Glue', emoji: '🧪', category: Category.MATERIAL },
    { id: 'mat5', label: 'Sponge', emoji: '🧽', category: Category.MATERIAL },
    { id: 'mat6', label: 'Paint', emoji: '🎨', category: Category.MATERIAL },
    { id: 'mat7', label: 'Paintbrush', emoji: '🖌️', category: Category.MATERIAL },
    { id: 'mat8', label: 'Scissors', emoji: '✂️', category: Category.MATERIAL },
    { id: 'mat9', label: 'Tape', emoji: '🎞️', category: Category.MATERIAL },
    { id: 'mat10', label: 'Stickers', emoji: '🌈', category: Category.MATERIAL },
    { id: 'mat11', label: 'Stone', emoji: '🪨', category: Category.MATERIAL },
    { id: 'mat12', label: 'Glass', emoji: '🍷', category: Category.MATERIAL },
    { id: 'mat13', label: 'Diamond', emoji: '💎', category: Category.MATERIAL },
    { id: 'mat14', label: 'Ruby', emoji: '🧣', category: Category.MATERIAL },
  ],

  [Category.IS_BE]: [
    { id: 'ib1', label: 'Is', emoji: '🔹', category: Category.IS_BE },
    { id: 'ib2', label: 'Am', emoji: '🙋', category: Category.IS_BE },
    { id: 'ib3', label: 'Are', emoji: '👥', category: Category.IS_BE },
    { id: 'ib4', label: 'Was', emoji: '⏪', category: Category.IS_BE },
    { id: 'ib5', label: 'Be', emoji: '♾️', category: Category.IS_BE },
    { id: 'ib6', label: 'Grow', emoji: '🌱', category: Category.IS_BE },
    { id: 'ib7', label: 'Happy', emoji: '😊', category: Category.IS_BE },
    { id: 'ib8', label: 'Silly', emoji: '🤪', category: Category.IS_BE },
    { id: 'ib9', label: 'Excited', emoji: '🤩', category: Category.IS_BE },
    { id: 'ib10', label: 'Confused', emoji: '😵‍💫', category: Category.IS_BE },
    { id: 'ib11', label: 'Sad', emoji: '😢', category: Category.IS_BE },
    { id: 'ib12', label: 'Sick', emoji: '🤒', category: Category.IS_BE },
    { id: 'ib13', label: 'Shy', emoji: '😳', category: Category.IS_BE },
    { id: 'ib14', label: 'Nervous', emoji: '😰', category: Category.IS_BE },
    { id: 'ib15', label: 'Frustrated', emoji: '😤', category: Category.IS_BE },
    { id: 'ib16', label: 'Smart', emoji: '💡', category: Category.IS_BE },
    { id: 'ib17', label: 'Scared', emoji: '😨', category: Category.IS_BE },
    { id: 'ib18', label: 'Hurt', emoji: '🤕', category: Category.IS_BE },
    { id: 'ib19', label: 'Busy', emoji: '🏃', category: Category.IS_BE },
    { id: 'ib20', label: 'Tired', emoji: '🥱', category: Category.IS_BE },
    { id: 'ib21', label: 'Ready', emoji: '🏁', category: Category.IS_BE },
    { id: 'ib22', label: 'Nice', emoji: '😇', category: Category.IS_BE },
  ],

  [Category.LOOK]: [
    { id: 'lk1', label: 'Big', emoji: '🐘', category: Category.LOOK },
    { id: 'lk2', label: 'Little', emoji: '🐭', category: Category.LOOK },
    { id: 'lk3', label: 'Near', emoji: '🤏', category: Category.LOOK },
    { id: 'lk4', label: 'Far', emoji: '🔭', category: Category.LOOK },
    { id: 'lk5', label: 'In', emoji: '📥', category: Category.LOOK },
    { id: 'lk6', label: 'Out', emoji: '📤', category: Category.LOOK },
    { id: 'lk7', label: 'Easy', emoji: '🍰', category: Category.LOOK },
    { id: 'lk8', label: 'Difficult', emoji: '🧗', category: Category.LOOK },
    { id: 'lk9', label: 'On', emoji: '💡', category: Category.LOOK },
    { id: 'lk10', label: 'Off', emoji: '🌑', category: Category.LOOK },
    { id: 'lk11', label: 'Same', emoji: '👯', category: Category.LOOK },
    { id: 'lk12', label: 'Different', emoji: '🔀', category: Category.LOOK },
    { id: 'lk13', label: 'Watch', emoji: '👁️', category: Category.LOOK },
    { id: 'lk14', label: 'Favorite', emoji: '⭐', category: Category.LOOK },
    { id: 'lk15', label: 'Fun', emoji: '🥳', category: Category.LOOK },
    { id: 'lk16', label: 'Boring', emoji: '😴', category: Category.LOOK },
    { id: 'lk17', label: 'Fast', emoji: '⚡', category: Category.LOOK },
    { id: 'lk18', label: 'Slow', emoji: '🐢', category: Category.LOOK },
    { id: 'lk19', label: 'Hot', emoji: '🔥', category: Category.LOOK },
    { id: 'lk20', label: 'Cold', emoji: '❄️', category: Category.LOOK },
  ],

  [Category.WEAR]: [
    { id: 'wr1', label: 'Hat', emoji: '🎩', category: Category.WEAR },
    { id: 'wr2', label: 'Coat', emoji: '🧥', category: Category.WEAR },
    { id: 'wr3', label: 'Shirt', emoji: '👕', category: Category.WEAR },
    { id: 'wr4', label: 'Dress', emoji: '👗', category: Category.WEAR },
    { id: 'wr5', label: 'Pants', emoji: '👖', category: Category.WEAR },
    { id: 'wr6', label: 'Shoes', emoji: '👟', category: Category.WEAR },
    { id: 'wr7', label: 'Socks', emoji: '🧦', category: Category.WEAR },
    { id: 'wr8', label: 'Underwear', emoji: '🩲', category: Category.WEAR },
    { id: 'wr9', label: 'Clothes', emoji: '👔', category: Category.WEAR },
    { id: 'wr10', label: 'Pajamas', emoji: '🛌', category: Category.WEAR },
    { id: 'wr11', label: 'Body', emoji: '👤', category: Category.WEAR },
    { id: 'wr12', label: 'Wardrobe', emoji: '🚪', category: Category.WEAR },
    { id: 'wr13', label: 'Touch', emoji: '🖐️', category: Category.WEAR },
    { id: 'wr14', label: 'Wear', emoji: '👗', category: Category.WEAR },
    { id: 'wr15', label: 'Put On', emoji: '🧤', category: Category.WEAR },
    { id: 'wr16', label: 'Take Off', emoji: '🧣', category: Category.WEAR },
    { id: 'wr17', label: 'Get Dressed', emoji: '👔', category: Category.WEAR },
    { id: 'wr18', label: 'Undress', emoji: '🧺', category: Category.WEAR },
    { id: 'wr19', label: 'Handsome', emoji: '🤵', category: Category.WEAR },
    { id: 'wr20', label: 'Pretty', emoji: '💃', category: Category.WEAR },
    { id: 'wr21', label: 'Ugly', emoji: '👹', category: Category.WEAR },
  ],

  [Category.BODY]: [
    { id: 'bd1', label: 'Head', emoji: '👤', category: Category.BODY },
    { id: 'bd2', label: 'Hair', emoji: '💇', category: Category.BODY },
    { id: 'bd3', label: 'Mouth', emoji: '👄', category: Category.BODY },
    { id: 'bd4', label: 'Teeth', emoji: '🦷', category: Category.BODY },
    { id: 'bd5', label: 'Tongue', emoji: '👅', category: Category.BODY },
    { id: 'bd6', label: 'Face', emoji: '😊', category: Category.BODY },
    { id: 'bd7', label: 'Chest', emoji: '👕', category: Category.BODY },
    { id: 'bd8', label: 'Back', emoji: '🎒', category: Category.BODY },
    { id: 'bd9', label: 'Stomach', emoji: '🤰', category: Category.BODY },
    { id: 'bd10', label: 'Bottom', emoji: '🍑', category: Category.BODY },
    { id: 'bd11', label: 'Hand', emoji: '🖐️', category: Category.BODY },
    { id: 'bd12', label: 'Finger', emoji: '☝️', category: Category.BODY },
    { id: 'bd13', label: 'Arm', emoji: '💪', category: Category.BODY },
    { id: 'bd14', label: 'Leg', emoji: '🦵', category: Category.BODY },
    { id: 'bd15', label: 'Foot', emoji: '🦶', category: Category.BODY },
    { id: 'bd16', label: 'Body', emoji: '🧍', category: Category.BODY },
    { id: 'bd17', label: 'Private Parts', emoji: '🔒', category: Category.BODY },
    { id: 'bd18', label: 'Me', emoji: '🙋', category: Category.BODY },
    { id: 'bd19', label: 'Mine', emoji: '👈', category: Category.BODY },
  ],

  [Category.TOUCH]: [
    { id: 'tc1', label: 'Touch', emoji: '🖐️', category: Category.TOUCH },
    { id: 'tc2', label: 'Finish', emoji: '🏁', category: Category.TOUCH },
    { id: 'tc3', label: 'Open', emoji: '🔓', category: Category.TOUCH },
    { id: 'tc4', label: 'Close', emoji: '🔒', category: Category.TOUCH },
    { id: 'tc5', label: 'Wash', emoji: '🧼', category: Category.TOUCH },
    { id: 'tc6', label: 'Clean', emoji: '✨', category: Category.TOUCH },
    { id: 'tc7', label: 'Fix', emoji: '🔧', category: Category.TOUCH },
    { id: 'tc8', label: 'Show', emoji: '📽️', category: Category.TOUCH },
    { id: 'tc9', label: 'Break', emoji: '💔', category: Category.TOUCH },
    { id: 'tc10', label: 'Cut', emoji: '✂️', category: Category.TOUCH },
    { id: 'tc11', label: 'Made', emoji: '🏗️', category: Category.TOUCH },
    { id: 'tc12', label: 'Tall', emoji: '🦒', category: Category.TOUCH },
    { id: 'tc13', label: 'Short', emoji: '🐜', category: Category.TOUCH },
    { id: 'tc14', label: 'Straight', emoji: '📏', category: Category.TOUCH },
    { id: 'tc15', label: 'Crooked', emoji: '🌀', category: Category.TOUCH },
    { id: 'tc16', label: 'Wet', emoji: '💧', category: Category.TOUCH },
    { id: 'tc17', label: 'Soft', emoji: '🧸', category: Category.TOUCH },
    { id: 'tc18', label: 'Dirty', emoji: '💩', category: Category.TOUCH },
    { id: 'tc19', label: 'New', emoji: '🎁', category: Category.TOUCH },
    { id: 'tc20', label: 'Old', emoji: '👴', category: Category.TOUCH },
    { id: 'tc21', label: 'Sharp', emoji: '🔪', category: Category.TOUCH },
    { id: 'tc22', label: 'Dull', emoji: '✏️', category: Category.TOUCH },
  ],

  [Category.PEOPLE]: [
    { id: 'pe1', label: 'He', emoji: '👨', category: Category.PEOPLE },
    { id: 'pe2', label: 'She', emoji: '👩', category: Category.PEOPLE },
    { id: 'pe3', label: 'We', emoji: '👥', category: Category.PEOPLE },
    { id: 'pe4', label: 'They', emoji: '👪', category: Category.PEOPLE },
    { id: 'pe5', label: 'Who', emoji: '❓', category: Category.PEOPLE },
    { id: 'pe6', label: 'Relationship', emoji: '🤝', category: Category.PEOPLE },
    { id: 'pe7', label: 'Grandma', emoji: '👵', category: Category.PEOPLE },
    { id: 'pe8', label: 'Grandpa', emoji: '👴', category: Category.PEOPLE },
    { id: 'pe9', label: 'Mother', emoji: '👩‍🍼', category: Category.PEOPLE },
    { id: 'pe10', label: 'Father', emoji: '👨‍🍼', category: Category.PEOPLE },
    { id: 'pe11', label: 'Sister', emoji: '👧', category: Category.PEOPLE },
    { id: 'pe12', label: 'Brother', emoji: '👦', category: Category.PEOPLE },
    { id: 'pe13', label: 'Family', emoji: '🏠', category: Category.PEOPLE },
    { id: 'pe14', label: 'Boy', emoji: '👦', category: Category.PEOPLE },
    { id: 'pe15', label: 'Girl', emoji: '👧', category: Category.PEOPLE },
    { id: 'pe16', label: 'Baby', emoji: '👶', category: Category.PEOPLE },
    { id: 'pe17', label: 'Friend', emoji: '🤝', category: Category.PEOPLE },
    { id: 'pe18', label: 'Teacher', emoji: '👩‍🏫', category: Category.PEOPLE },
    { id: 'pe19', label: 'Cook', emoji: '👨‍🍳', category: Category.PEOPLE },
    { id: 'pe20', label: 'Doctor', emoji: '👨‍⚕️', category: Category.PEOPLE },
    { id: 'pe21', label: 'Aide', emoji: '🩹', category: Category.PEOPLE },
    { id: 'pe22', label: 'Police Officer', emoji: '👮', category: Category.PEOPLE },
    { id: 'pe23', label: 'Fireman', emoji: '👨‍🚒', category: Category.PEOPLE },
  ],

  [Category.WHAT]: [
    { id: 'w1', label: 'What', emoji: '❓', category: Category.WHAT },
    { id: 'w2', label: 'How', emoji: '⚙️', category: Category.WHAT },
    { id: 'w3', label: 'Which', emoji: '↔️', category: Category.WHAT },
    { id: 'w4', label: 'Why', emoji: '🔍', category: Category.WHAT },
    { id: 'w5', label: 'Can', emoji: '🔋', category: Category.WHAT },
    { id: 'w6', label: 'Will', emoji: '🔮', category: Category.WHAT },
    { id: 'w7', label: 'The', emoji: '🎯', category: Category.WHAT },
    { id: 'w8', label: 'A', emoji: '🍎', category: Category.WHAT },
    { id: 'w9', label: 'Some', emoji: '🍿', category: Category.WHAT },
    { id: 'w10', label: 'More', emoji: '➕', category: Category.WHAT },
    { id: 'w11', label: 'Other', emoji: '🔘', category: Category.WHAT },
    { id: 'w12', label: 'Much', emoji: '🌊', category: Category.WHAT },
    { id: 'w13', label: 'All', emoji: '🌎', category: Category.WHAT },
    { id: 'w14', label: 'Any', emoji: '🎲', category: Category.WHAT },
    { id: 'w15', label: 'Every', emoji: '📅', category: Category.WHAT },
    { id: 'w16', label: 'Many', emoji: '👨‍👩‍👧‍👦', category: Category.WHAT },
    { id: 'w17', label: 'These', emoji: '👇', category: Category.WHAT },
    { id: 'w18', label: 'Those', emoji: '👉', category: Category.WHAT },
    { id: 'w19', label: 'Another', emoji: '🔄', category: Category.WHAT },
  ],

  [Category.WHEN]: [
    { id: 'wn1', label: 'Second', emoji: '⏱️', category: Category.WHEN },
    { id: 'wn2', label: 'Minute', emoji: '⏲️', category: Category.WHEN },
    { id: 'wn3', label: 'Hour', emoji: '🕰️', category: Category.WHEN },
    { id: 'wn4', label: 'Day', emoji: '📅', category: Category.WHEN },
    { id: 'wn5', label: 'Week', emoji: '📆', category: Category.WHEN },
    { id: 'wn6', label: 'Month', emoji: '🗓️', category: Category.WHEN },
    { id: 'wn7', label: 'Year', emoji: '📜', category: Category.WHEN },
    { id: 'wn8', label: 'Yesterday', emoji: '⏪', category: Category.WHEN },
    { id: 'wn9', label: 'Today', emoji: '📍', category: Category.WHEN },
    { id: 'wn10', label: 'Tomorrow', emoji: '⏩', category: Category.WHEN },
    { id: 'wn11', label: 'Night', emoji: '🌃', category: Category.WHEN },
    { id: 'wn12', label: 'Now', emoji: '⚡', category: Category.WHEN },
    { id: 'wn13', label: 'Later', emoji: '⏳', category: Category.WHEN },
    { id: 'wn14', label: 'Before', emoji: '⬅️', category: Category.WHEN },
    { id: 'wn15', label: 'After', emoji: '➡️', category: Category.WHEN },
    { id: 'wn16', label: 'When', emoji: '❓', category: Category.WHEN },
    { id: 'wn17', label: 'Spring', emoji: '🌱', category: Category.WHEN },
    { id: 'wn18', label: 'Summer', emoji: '☀️', category: Category.WHEN },
    { id: 'wn19', label: 'Fall', emoji: '🍂', category: Category.WHEN },
    { id: 'wn20', label: 'Winter', emoji: '❄️', category: Category.WHEN },
    { id: 'wn21', label: 'Time', emoji: '⏳', category: Category.WHEN },
    { id: 'day1', label: 'Monday', emoji: '📅', category: Category.WHEN },
    { id: 'day2', label: 'Tuesday', emoji: '📅', category: Category.WHEN },
    { id: 'day3', label: 'Wednesday', emoji: '📅', category: Category.WHEN },
    { id: 'day4', label: 'Thursday', emoji: '📅', category: Category.WHEN },
    { id: 'day5', label: 'Friday', emoji: '📅', category: Category.WHEN },
    { id: 'day6', label: 'Saturday', emoji: '📅', category: Category.WHEN },
    { id: 'day7', label: 'Sunday', emoji: '📅', category: Category.WHEN },
  ],
};
